name: GitHub Pages

on: push

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: improve-docs

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '17'

      - run: npm ci
      - run: npm run build-docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./jsdoc