name: Run tests

on: 
  push:
    branches: [gh-pages]

jobs:  
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/github-script@v6
        id: latest_ver
        with:
          script: |
            function semverCompare(a, b) {
              if (a.startsWith(b + "-")) return -1
              if (b.startsWith(a + "-")) return  1
              return a.localeCompare(b, undefined, { numeric: true, sensitivity: "case", caseFirst: "upper" })
            }
            const globber = await glob.create('docs/v*');
            const files = await globber.glob();
            const versions = files.map(f => f.slice(1));
            versions.sort(semverCompare);
            return versions.pop();
          result-encoding: string
      - name: Get result
        run: echo "${{steps.latest_ver.outputs.result}}"      
      - name: add files
        run: |
          git config --global user.name '${{ github.actor }}'
          git config --global user.email '${{ github.actor }}@users.noreply.github.com'
          git commit -am "Update html redirect"
          git push