name: Release

on: 
  workflow_run:
    workflows: [Run Tests]
    types: [completed]
    branches: [master, main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: ButlerLogic/action-autotag@1.1.1
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          tag_prefix: "v"
        id: create_tag
      - run: echo ${{ steps.create_tag.outputs.tagname }}
      - run: echo ${{ steps.create_tag.outputs.version }}
      - name: check if a new tag is created
        run: "[[ '${{ steps.create_tag.outputs.tagname }}' ]]"
      - name: get major-minor version
        id: docver
        run: echo "DOCVER=${TAGNAME%.*}" >> $GITHUB_ENV 
        env:
          TAGNAME: ${{ steps.create_tag.outputs.tagname }}
        # uses: actions/github-script@v6
        # with:
        #   result-encoding: string
        #   script: var s = process.env.TAGNAME; return s.slice(0, s.lastIndexOf('.'))
      - run: echo "$DOCVER"
      - run: echo npm ci
      - name: Publish package on NPM
        run: echo npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
